%% File: test_trial.m
% Construct with modules (floating assumption)
clc; clear variables; close all;
addpath('lib');
addpath('lib/display'); addpath('lib/log');
addpath('lib/alg'); addpath('lib/alg/connect');

%% Initialization
str1='shapehalf-robot6-target6-method1-time';
N_run = 30;
for i = 1:N_run
    str2=num2str(i);
    name=[str1 str2]
    trial = Trial(name);
    
    % Map
    Map_Size = [24, 24]; % length*widthhalf
    
    % Robots
    robot_locs = [10,2;2,10;14,22;22,18;22,14;22,10];
    dock = [1,0,0,1;...
            1,0,0,1;...
            0,1,0,1;...
            1,0,1,0;...
            0,1,1,0;...
            0,1,1,0;...
            ]; % up, down, left, right
    % Targets
     tar_locs = [ 11,11;11,12;11,13;12,11;12,12;12,13 ];
    try
        trial.run("RobotLocation", robot_locs, ...
            "RobotDock", dock, ...
            "TargetLocation", tar_locs,...
            "MapSize", Map_Size, ...
            "AlgorithmType", 1, ...
            "isLogging", [true, true], ...
            "TargetCenter", 12 ...
        );
    catch e
        disp(e);
    end
end